curl --location --globoff 'https://api.levels.fyi/v3/salary/search?minYearsOfExp=2&maxYearsOfExp=4&companySlug=bytedance&limit=50&sortBy=offer_date&sortOrder=DESC&jobFamilySlug=software-engineer&currency=USD&dmaIds[]=807' \
--header 'Accept: application/json, text/plain, */*' \
--header 'Accept-Language: en-US,en;q=0.9' \
--header 'Authorization: Bearer eyJraWQiOiJJaFplZEtLU3hDVkFDSmJaMTkra1wvQVJNWm5yVHZiMDZlYTZTMGFOeXo4UT0iLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiI2ZTdiMGRmYi0xNDI5LTRjNTctODA2MS0xZDdkMzA4YTYz' \
--header 'Connection: keep-alive' \
--header 'Origin: https://www.levels.fyi' \
--header 'Referer: https://www.levels.fyi/' \
--header 'Sec-Fetch-Dest: empty' \
--header 'Sec-Fetch-Mode: cors' \
--header 'Sec-Fetch-Site: same-site' \
--header 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/145.0.0.0 Safari/537.36' \
--header 'sec-ch-ua: "Chromium";v="145", "Not:A-Brand";v="99"' \
--header 'sec-ch-ua-mobile: ?0' \
--header 'sec-ch-ua-platform: "macOS"' \
--header 'x-agent: levelsfyi_website'
